### ISSUE TITLE
medical and psychological help

### ISSUE THREAD

**Issue by DoktorZhuchara** [ScienceFun/Kerbalism-Continued#11]
sorry for Google translator.
maybe someone thinks this is a bad idea, but it can be done optionally, or explain to me just how radiation accumulation and stress work. I myself could not understand at what exact moment this happens in the source code, only found an approximate piece but could not figure out what variable it was responsible for. in general, little I understood -__-
laboratory at the moment:
the essence of the laboratory is to clean the samples and send them home, but if you consider that in any case you need to return home ... the laboratory can be considered an unnecessary load. it allows you to get before you get what you already get (if you did not send the green men to one end of T__T). in general, substantial benefits are only to cruel people =) Yes, you can still raise the level, but I'm inclined to the fact that it's still not worth the effort and that mass in the long run.

my idea is this:

that if there is or is still some detail (the regime for the standard laboratory) at which if there is a physician (scientist), then there will be a slow rehabilitation of the kerbalov. It would also be great if their health improved when the environment changed to favorable. if a person received a share of radiation, then it became worse, but if he was placed in ideal conditions and the injuries received were not critical, then he would get a little better.

yet it would not be bad to add to the intefe, when you direct on "stress" / "radiation" what would be a timer with when there will be a critical level with such a modification of the parameter. as occurs with food / oxygen and so on.

I hope for any help from your side, sorry for Google translator.
in theory I could help with the code, but I did not understand all the moments, and I do not have enough knowledge to learn the most patience and knowledge is not enough.

I was also interested in the question of whether it is possible to make remote tech integration into the communication system that comes with it. not the murder of one of them, but integration. Well, it's already so ... remembered

-----------------------------------------------------------------------------------------------------------------
простите за гугл переводчик.
возможно кто-то считает это плохой идеей, но это можно сделать опционально, или обясните ме просто как работает накапливание радиации и стресс. я сам не смог понять в какой именно момент это происходит в исходном коде, только нашел примерный кусок но не смог понять какая переменная за что отвечает. в общем мало что я понял -__-
лаборатория на данный момент:
суть лаборатории в том, что бы очистить образцы и отправить их домой, но если учесть, что в любом случае нужно вернутся домой...лабораторию можно считать ненужной нагрузкой. она позволяет получить тебе получить раньше то, что ты и так получишь(если не отправил зелененький человечков в один конец Т__Т). в общем существенная выгода есть только жестоким людям =) да, можно еще повысть уровень, но я склоняюсь к тому, что это все равно не стоит тех усилий и той массы в долгосрочной перспективе. 

моя идея в следующем:

что если будет или еще какая либо деталь(режим для стандартной лаборатории) при котором если там медик(ученый), то будет происходить медленная реабилитация кербалов. Так же было бы замечательно, если их хдоровье улучшалой при смене среды на благоприятную. если человек получил долю радиации, то ему стало хуже, но если его поместить в идеальные уловия и полученные повреждения не были критическими, то ему будет стоновится хоть немного лучше. 

еще было бы не плохо добавить в интефей, когда наводишь на "стресс" / "радиацию" что бы был таймер с тем, когда будет критиский уровень при такой модикации параметра. как происходит с пищей/кислородом и тд.

надеюсь на  любую помощь с вашей стороны, простите за гугл переводчик.
в теории я мог бы помочь с кодом, но я не все моменты понял, а изучать самому терпения не хватает и знания не достаточно . 

так же меня интересовал вопрос можно ли сделать интеграцию remote tech в ту систему связи, что идет в комплекте. не убийство одной из них, а интеграцию. ну это уже так...вспомнилось

**Comment by HaullyGames** [comment]
Hi @DoktorZhuchara,

We can have a discuss about your ideas, but it should be through [KSP Forum](https://forum.kerbalspaceprogram.com/index.php?/topic/137227-130-kerbalism-v129/&) with all interested.
I'm closing this issue.
