### ISSUE TITLE
Resources anomaly draining 

### ISSUE THREAD

**Issue by daorse** [ScienceFun/Kerbalism-Continued#15]
Hi,
I’ve read other posts about issues very similar to mine, I reckon my problem is probably due to a conflict between Kerbalism and another mod of the many installed, but I’d really love to find a solution to this without having to remove one of them. How do you suggest to proceed? Is there a way to manually change and simplify the algorithm and/or reducing it at something very linear like vanilla power consumption?
Thank you in advance

**Comment by lordcirth** [comment]
Post a gist of KSP.log, and your modlist.

**Comment by daorse** [comment]
[KSP.log](https://github.com/ScienceFun/Kerbalism-Continued/files/1759676/KSP.log)
As I mentioned I've quite a few mods installed but as far as is possible I'd like to keep all of them.. I know it's not easy but hopefully not impossible.
Thank you again

Edit:
The problem is due to Kerbal Atomics or/and Cryogenic Engines. Any idea about how I could solve this interference? 



ModuleManager v3.0.4.0 = True
		MiniAVC v1.0.3.2 = True
		aaa_Toolbar v1.7.14.0 = True
		AmbientLightAdjustment v2.6.3.8 = True
		MiniAVC v1.0.3.0 = True
		B9AnimationModules v1.0.7.0 / v1.0.7 = True
		B9PartSwitch v1.9.0.0 = True
		BetterBurnTime v1.0.0.0 = True
		CareerManager v1.3.3.0 = True
		ChampagneBottle v0.3.6.0 / v1.0.0.0 = True
		Chatterer v0.9.93.1804 = True
		CommunityTraitIcons v0.1.9.0 = True
		ContractConfigurator v1.0.0.0 / v1.23.2 = True
		RemoteTech v1.8.0.0 / v1.8.8 = True
		CC_RemoteTech v1.0.0.0 / v1.23.2 = True
		CrewLight v1.0.6474.20539 = True
		SimpleBoiloff v0.2.1.0 = True
		DeployableEngines v2.2.0.0 = True
		DistantObject v1.9.1.24206 = True
		DMagic v1.3.0.9 / vv1.3.9 = True
		DynamicBatteryStorage v1.0.0.0 = True
		Atmosphere v1.2.2.1 = True
		CelestialShadows v1.2.2.1 = True
		CityLights v1.2.2.1 = True
		EVEManager v1.2.2.1 = True
		PartFX v1.2.2.1 = True
		PQSManager v1.2.2.1 = True
		ShaderLoader v1.2.2.1 = True
		Terrain v1.2.2.1 = True
		TextureConfig v1.2.2.1 = True
		Utils v1.2.2.1 = True
		_BuildManager v1.2.2.1 = True
		Firespitter v7.3.6354.39102 = True
		HideEmptyTechTreeNodes v1.0.0.0 = True
		RasterPropMonitor v0.29.3.14830 = True
		Kerbalism v1.2.9.0 = True
		KerbalJointReinforcement v3.3.3.0 = True
		HyperEdit v1.5.4.0 = True
		ModularFlightIntegrator v1.0.0.0 / v1.2.4.0 = True
		Kopernicus.Components v1.0.0.0 = True
		Kopernicus.OnDemand v1.0.0.0 = True
		Kopernicus.Parser v1.0.0.0 = True
		Kopernicus v1.0.0.0 = True
		MechJeb2 v2.5.1.0 / v / v2.7.0.0 = True
		NearFutureElectrical v1.0.0.0 = True
		NearFuturePropulsion v0.9.0.0 = True
		NearFutureSolar v0.4.0.0 = True
		FinalFrontier v1.0.0.0 = True
		PortraitStats v1.0.15.0 = True
		RcsSounds v5.2.0.0 = True
		RealChute v1.4.6361.26777 / v1.4.4.0 = True
		SolverEngines v3.3.0.0 = True
		RealFuels v0.12.3.41047 / v0.12.3.1 = True
		ReentryParticleEffect v1.2.0.0 = True
		MiniAVC v1.0.3.3 = True
		DeepFreeze v0.23.6.0 = True
		SCANsat v1.8.4.0 / vv18.4 = True
		SCANmechjeb v1.8.4.0 / vv18.4 = True
		SCANsat.Unity v1.8.4.0 = True
		scatterer v1.0.6396.38553 = True
		SmokeScreen v2.7.6.1 = True
		TextureReplacer v2.6.0.0 = True
		Scale v2.3.7.0 = True
		Scale_Redist v1.0.0.0 = True
		VesselView v0.8.5.1 / v1.0.0.0 = True
		VesselViewRPM v0.8.5.1 / v1.0.0.0 = True
		VVDiscoDisplay v0.8.5.1 / v1.0.0.0 = True
		VVPartSelector v0.8.5.1 / v1.0.0.0 = True
		000_Toolbar = True
		Ablative-Airbrake = True
		AmbientLightAdjustment = True
		B9AnimationModules = True
		B9PartSwitch = True
		B9_Aerospace = True
		BetterBurnTime = True
		CareerManager = True
		Champagne = True
		Chatterer = True
		CommunityResourcePack = True
		CommunityTechTree = True
		CommunityTraitIcons = True
		ContractConfigurator = True
		ContractPacks = True
		CrewLight = True
		CryoEngines = True
		CryoTanks = True
		DeployableEngines = True
		DistantObject = True
		DMagicOrbitalScience = True
		DynamicBatteryStorage = True
		EnvironmentalVisualEnhancements = True
		Firespitter = True
		HeatControl = True
		HideEmptyTechTreeNodes = True
		JSI = True
		KerbalAtomics = True
		Kerbalism = True
		KerbalJointReinforcement = True
		Kerbaltek = True
		Kopernicus = True
		KWRocketry = True
		MechJeb2 = True
		ModularFlightIntegrator = True
		NearFutureConstruction = True
		NearFutureElectrical = True
		NearFutureLaunchVehicles = True
		NearFutureProps = True
		NearFuturePropulsion = True
		NearFutureSolar = True
		NearFutureSpacecraft = True
		Nereid = True
		PortraitStats = True
		RcsSounds = True
		RealChute = True
		RealFuels = True
		RealFuels-Stockalike = True
		RealPlume = True
		RealPlume-RFStockalike = True
		ReentryParticleEffect = True
		RemoteTech = True
		REPOSoftTech = True
		SCANsat = True
		scatterer = True
		SmokeScreen = True
		SolverEngines = True
		StockVisualEnhancements = True
		SVT = True
		TextureReplacer = True
		TweakScale = True
		VesselView = True
		zzRFStockalike = True
		MechJebAndEngineerForAll.cfg = True
		ModuleManager.3.0.4.dll = True

**Comment by lordcirth** [comment]
The CryoTanks bug is fixed in the alpha release:
https://github.com/ScienceFun/Kerbalism-Continued/releases

Remove Kerbalism and install the alpha manually, and you should be fine.

**Comment by daorse** [comment]
Thanks, it works now.

**Comment by HaullyGames** [comment]
Thanks @lordcirth for your support.
