### ISSUE TITLE
Can't enter pod after EVA. "Command pod is full"

### ISSUE THREAD

**Issue by ghost** [ScienceFun/Kerbalism-Continued#16]
After EVA i cannot enter to my command pod, because the game says it's full, even though it shouldn't. Clicking when the hatch it displays, that there's 0/0 space left. In VAB it displays the crew capacity correctly. Also SAS doesn't work, even though I have skilled pilot on board.

![screenshot4](https://user-images.githubusercontent.com/36902367/36757890-5fa43bea-1c1b-11e8-90b6-f3bc8dbc8c39.png)
![screenshot1](https://user-images.githubusercontent.com/36902367/36757891-5fd99f1a-1c1b-11e8-85e1-24ba6ed3b404.png)
![screenshot2](https://user-images.githubusercontent.com/36902367/36757893-5ff6cd56-1c1b-11e8-9d5c-e33f14148d7d.png)

This problem started after switching from original Kerbalism to this version.

Modlist;
[Modlist.txt](https://github.com/ScienceFun/Kerbalism-Continued/files/1764901/Modlist.txt)

**Comment by ghost** [comment]
I'll try to find the possible mod causing this later.

**Comment by lordcirth** [comment]
ConnectedLivingSpace seems like a likely conflict; try removing that first.

**Comment by lordcirth** [comment]
Nevermind, Haully thinks he found the bug.

**Comment by ghost** [comment]
Removing ConnectedLivingSpace didn't fix the problem. I tried in a new save.

**Comment by ghost** [comment]
I uninstalled all the mods except Kerbalism and ModuleManager 3.0.4. The problem still exists. Can't enter the pod, but SAS works. 

EDIT: The bug got fixed when I uninstalled Kerbalism and ModuleManager.

**Comment by lordcirth** [comment]
Yeah, Haully found the bug in the change he made to support inflatable habitats.  I ran into the bug too, but in VAB.  It should be fixed soon.

**Comment by HaullyGames** [comment]
This bug should be fixed by the last release.
