### ISSUE TITLE
Update Bluedog_DB support

### ISSUE THREAD

**Issue by HaullyGames** [ScienceFun/Kerbalism-Continued#3]
The **GameData\Kerbalism\Support\Bluedog.cfg** file needs to be reviewed and updated.

**Comment by reviest** [comment]
I've started patching antennas. Unfortunately, very busy weekend.

**Comment by HaullyGames** [comment]
I've worked on antenna parts, don't worry about antenna support, I updated.

**Comment by HaullyGames** [comment]
Hi @reviest.

.cfg has been updated.

Please re-open this issue if you found any other issue with Bluedog_DB.
