### ISSUE TITLE
Reaction wheels

### ISSUE THREAD

**Issue by reviest** [ScienceFun/Kerbalism-Continued#7]
I think it would be more realistic to delete Reaction wheels module from probes/pods and make it obligatory to use RCS instead. It also might balance some fast EC consumption, since AdvancedEC makes reaction wheels very energy-dependant.

**Comment by HaullyGames** [comment]
AdvancedEC doesn't affect reaction wheels.

**Comment by reviest** [comment]
My bad. I guees Squad did something in last updates.
